### ISSUE TITLE
Laravel-paginateroute is not working in laravel 5.2 and page number is not increase.

### ISSUE THREAD

**Issue by Vongsi** [spatie/laravel-paginateroute#12]
Hi Team

Thanks for such a greate extension plugin. It is something that I am looking for.

I have followed the instruction on this page and installed the extension successfully, unfortunately it did not work for me.

**My routes**

Route::get('photo/', ['uses' => 'PhotoController@index']);

Route::get('photo/page/{page}', ['uses' => 'PhotoController@index']);

**Method in my controller**

public function index() {
       $photos = Photo::orderBy('created_at', 'desc')->simplePaginate(15);

```
    $data['title'] = "SITE NAME | PHOTO";
    $data['page_content'] = 'YOU ARE VIEWING PHOTOS';
    $data['photos'] = $photos;

    if (view()->exists('photos.index')) {
        return view('photos.index', $data);
    } else {
        return 'view photos.index is not existed.';
    }
```

}

Use below lines to generate the URLs

@if(PaginateRoute::hasPreviousPage())
<a href="{{ PaginateRoute::previousPageUrl() }}">Previous</a>  
@endif
@if(PaginateRoute::hasNextPage($photos))  
<a href="{{ PaginateRoute::nextPageUrl($photos) }}">Next</a>  
@endif

![image](https://cloud.githubusercontent.com/assets/1546091/14376229/ee48f14c-fd91-11e5-9e95-41f60292229c.png)

I can see the next link, but nothing happen after I clicked on it. 

After my first clicked, I noticed that it adds a new "page/2" to the end of the URL instead of change the page number from 2 to 3.

And also the page number doesn't increase ( _the page number should increased from 2 to 3, but still show 2_ ).

Below is the URL after my second click.

http://localhost/my-site-name/photo/page/2/page/2

Note: I am using laravel 5.2, and it is working fine if I use the default laravel pagination.

Any advices and helps are much appreciated

Thanks

**Comment by sebastiandedeyne** [comment]
Could you provide a full example of your blade view? (including the full link tag you're rendering)

**Comment by Vongsi** [comment]
Hi Sebastiandedeyne

Please see below

```
"require": {
//others extensions
        "spatie/laravel-paginateroute": "^2.2"
    },

'providers' => [
//others providers
        Spatie\PaginateRoute\PaginateRouteServiceProvider::class,
    ],

   'aliases' => [
//other aliases
        'PaginateRoute' => Spatie\PaginateRoute\PaginateRouteFacade::class,
    ],

```

**This is my index method in controller.**

```
public function index() {        

    //$photos = Photo::orderBy('created_at', 'desc')->Paginate(15);
    $photos = Photo::orderBy('created_at', 'desc')->simplePaginate(15);        

    $data['title'] = "SITE NAME | PHOTO";        
    $data['photos'] = $photos;        

    if (view()->exists('photos.index')) {

        return view('photos.index', $data);
    } else {
        return 'view photos.index is not existed.';
    }
}
```

**Below is the blade template I use to list all the photos and pagination**

```
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">    
        <div class="box box-primary box-no-shadow">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Photo
                </h3>
                <span class="pull-right"><a class="btn btn-default btn-flat" href="{{URL::to('/photo/album/')}}">Upload</a></span>                
            </div>
            <div class="box-body">
                <div class="row fbphotobox">
                    @foreach($photos as $photo)
                    <div class="col-xs-6 col-sm-3 col-md-2">
                        <a href="#" class="thumbnail"><img id="{{$photo->id}}" fbphotobox-id="{{$photo->id}}" class="photo" fbphotobox-src="{{$photo->photo_link}}" alt="{{$photo->photo_link}}" src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=200" width="150" height="200" /></a>
                    </div>
                    @endforeach

                </div>
            </div>
            <div class="box-footer">

                @if(PaginateRoute::hasPreviousPage())
                <a href="{{ PaginateRoute::previousPageUrl() }}">Previous</a>
                @endif

                @if(PaginateRoute::hasNextPage($photos))
                <a href="{{ PaginateRoute::nextPageUrl($photos) }}">Next</a>
                @endif

            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
```

**Note:**  I run my site as a sub folder in www folder in WAMP Server (http://localhost/my-site-name/).

Thanks

**Comment by sebastiandedeyne** [comment]
Sorry for never getting back to this, close this for now since it's been inactive for so long.

Feel free to reopen if you still need this issue resolved!
