### ISSUE TITLE
Problem with laravel 5.2 and language it

### ISSUE THREAD

**Issue by stefanodalpos** [spatie/laravel-paginateroute#13]
I install your code in my application, everything goes right but when i change my locale language in to "it"
`Argument 1 passed to Illuminate\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given, called in /home/vagrant/Code/XXXXX/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php on line 73 and defined
`

**Comment by sebastiandedeyne** [comment]
Apparently the `it` file provided was empty, which probably caused an error. I just tagged v2.2.2 which should fix the issue.

**Comment by stefanodalpos** [comment]
Yes resolved thanks!
