### ISSUE TITLE
Outdated docs! Non-static method Spatie\PaginateRoute\PaginateRoute::registerMacros() should not be called statically

### ISSUE THREAD

**Issue by torian257x** [spatie/laravel-paginateroute#15]
read your code, then read the docs. It won't work....

`Non-static method Spatie\PaginateRoute\PaginateRoute::registerMacros() should not be called statically`

**Comment by freekmurze** [comment]
The docs also mention to imported the `PaginateRoute` namespace. Did you do that?

``` php
use PaginateRoute;
```

**Comment by torian257x** [comment]
the error is naming the full path of the class.... otherwise it would say "class not found"

I do:

`use Spatie\PaginateRoute\PaginateRoute;` at the top of the file

**Comment by torian257x** [comment]
I run laravel 5.3 and php 7

**Comment by torian257x** [comment]
the code you provided is not the same any more of RouteServiceProvider.php:

you mentioned this:

```
public function boot(Router $router)
{
    parent::boot($router);
}
```

laravel 5.3 is this, that is before making the changes from your docs

```
    public function boot()
    {

      parent::boot();
    }
```

**Comment by freekmurze** [comment]
Try using

``` php
use PaginateRoute;
```

instead of 

``` php
use Spatie\PaginateRoute\PaginateRoute;
```

**Comment by cossssmin** [comment]
<strike>^ not working, the package is currently not compatible with 5.3...</strike>

I take that back, I've managed to solve it in Laravel 5.3.

The boot method is wrong in the docs, it should be this:

```
public function boot()
    {
        PaginateRoute::registerMacros();

        parent::boot();
    }
```
