### ISSUE TITLE
renderPageList() doesn't include any query string

### ISSUE THREAD

**Issue by ittikorns** [spatie/laravel-paginateroute#21]
I working on a search results page where each filter are submitting as GET method such as

`/search?min=100&max=5000`

However when using renderPageList() it strip out all of the query string instead of linking to 

`/search/page/2?min=100&max=5000`

It links to /search/page/2

Is there any reason of this or it's just something that have been missing from the function?

Workaround is I add another variable to renderPageList()

```
public function renderPageList(LengthAwarePaginator $paginator, $full = false, $class = null, $additionalLinks = false, $suffx = '') {
.
.
$url .= $suffix;
.
.
}
```

The question is I'm not sure is this the correct way in solving this problem?

**Comment by cossssmin** [comment]
+1, just stumbled across this now. How can we get it to preserve query strings?

**Comment by sebastiandedeyne** [comment]
Query strings currently aren't supported. We'd accept a PR that fixes this.
