### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by sh241** [spatie/laravel-paginateroute#23]
Hey!

I have a problem with routes in Laravel 5.3:

Route:
    Route::get('/genres/{alt}', ['as' => 'genres.show', 'uses' => 'GenreController@show']);
    Route::paginate('/genres', [ 'as' => 'genres.main', 'uses' => 'GenreController@index' ] );

So link http://mysite.com/genres/xxxx - working fine,
but links like http://mysite.com/genres/xxxx/page/x - are 404 error,
but links like http://mysite.com/genres/xxxx?page=x - working fine.

How to fix http://mysite.com/genres/xxxx/page/x ?

**Comment by sebastiandedeyne** [comment]
If there's a segment after `genres`, shouldn't it be:

```php
Route::paginate('/genres/{alt}', /* ... */);
```

**Comment by sh241** [comment]
Yes, but it render  http://mysite.com/genres/ link. ))))

**Comment by sebastiandedeyne** [comment]
What exactly renders that link?

**Comment by sh241** [comment]
'Route::get('/genres' )' renders 'http://mysite.com/genres' correct
'Route::get('/genres/{alt}' )' renders 'http://mysite.com/genres/{alt}' correct
'Route::paginate('/genres') ' renders 'http://mysite.com/genres/page/x' correct

'Route::paginate('/genres/{alt}')' - should render 'http://mysite.com/genres/{alt}/page/x', but
when I go to 'http://mysite.com/genres/{alt}/page/x' it loads content from 'http://mysite.com/genres/page/x'

------
My  signed routes:

Route::get('/genres' );
Route::get('/genres/{alt}' );
Route::paginate('/genres') ;
Route::paginate('/genres/{alt}') ;

**Comment by sh241** [comment]
Sorry. 

'http://mysite.com/genres/{alt}/page/x' loads 404 page.

**Comment by sebastiandedeyne** [comment]
What's the output of `php artisan route:list`?

**Comment by sh241** [comment]
```
|        | GET|HEAD | genres                         | genres               | App\Http\Controllers\GenreController@index    
          | web                                        |                                                                    
|        | GET|HEAD | genres/create                  |                      | App\Http\Controllers\GenreController@create   
          | web                                        |                                                                    
|        | GET|HEAD | genres/delete/{id}             |                      | App\Http\Controllers\GenreController@delete   
          | web                                        |                                                                    
|        | GET|HEAD | genres/edit/{id}               |                      | App\Http\Controllers\GenreController@edit     
          | web                                        |                                                                    
|        | POST     | genres/update/{id}             |                      | App\Http\Controllers\GenreController@update   
          | web                                        |                                                                    
|        | GET|HEAD | genres/{alt}                   | genre.show           | App\Http\Controllers\GenreController@show     
          | web                                        |                                                                    
|        | GET|HEAD | genres/{alt}/{pageQuery?}      | genres.pages         | App\Http\Controllers\GenreController@index    
          | web,Spatie\PaginateRoute\SetPageMiddleware |                                                                    
|        | POST     | genres/{id}/store              | genres.store         | App\Http\Controllers\CommentController@store  
          | web                                        |                                                                    
|        | GET|HEAD | genres/{pageQuery?}            | genres.main          | App\Http\Controllers\GenreController@index    
```

**Comment by sh241** [comment]
Ah! Sorry, bro.

Problem solved:
GenreController@index but should be GenreController@show. ))))

Sorry again. My fault. )))

**Comment by sebastiandedeyne** [comment]
No problem, glad to see it got resolved! :D
