### ISSUE TITLE
Call to undefined method Illuminate\Routing\Route::getUri()

### ISSUE THREAD

**Issue by Mrtenz** [spatie/laravel-paginateroute#26]
PaginateRoute.php line 295:
Call to undefined method Illuminate\Routing\Route::getUri()

I am using this code:
```{{ PaginateRoute::nextPageUrl($results) }}```

Using Laravel 5.4.

**Comment by sebastiandedeyne** [comment]
Hi, could you see if the latest version which I just released (2.4.1) resolves this issue?

**Comment by Mrtenz** [comment]
This fixed it, thanks!
