### ISSUE TITLE
Error Class 'Illuminate\Routing\RouteParameterBinder' not found after update from 2.2.2 to 2.4.1

### ISSUE THREAD

**Issue by mtx-z** [spatie/laravel-paginateroute#27]
Hello,

just as information, the package generate a error after updating from 2.2.2 to 2.4.1 on Laravel 5.1.
Error is Class 'Illuminate\Routing\RouteParameterBinder' not found.

Switching back to 2.2.2 fix the issue.

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this issue?

**Comment by freekmurze** [comment]
Experienced this issue when upgrading the package from `2.2.2` to the latest version in our `meta.be` app.

**Comment by codyphobe** [comment]
That class was added in 5.4.22 via laravel/framework@c906ed933713df22e4356cf4ea274f19b15d1ab7 and first used in this package as of 486e63578ed4cfb8c54c5c5ad47e001bfbf131b3 but there is neither a fallback for previous versions of Laravel nor a production version requirement for the `illuminate/routing` package in `composer.json`.

**Comment by reeslo** [comment]
I have the same issue 
ErrorException in PaginateRoute.php line 300: Class 'Illuminate\Routing\RouteParameterBinder' not found

**Comment by sebastiandedeyne** [comment]
Probably won't get to this myself soon, but we'd accept a PR with a fix anytime!
