### ISSUE TITLE
route function generate url error

### ISSUE THREAD

**Issue by hooklife** [spatie/laravel-paginateroute#31]
use 

`Route::get('video_list', 'Video\ListController@index')->name('video.list.index');`

`<a href="{{ route('video.list.index',['sort'=>'recorded_at-desc']) }}">new </a>`

result
`<a href="http://xxx.dev/video_list?sort=created_at-desc">new</a>`

---
use

`Route::paginate('video_list', 'Video\ListController@index')->name('video.list.index');`

`<a href="{{ route('video.list.index',['sort'=>'recorded_at-desc']) }}">new </a>`

result

 `<a href="http://xxx.dev/video_list/created_at-desc">new</a>`

i redirect to this url 404

**Comment by sebastiandedeyne** [comment]
Duplicate of #21
