### ISSUE TITLE
Links generate question marks

### ISSUE THREAD

**Issue by michaloravec** [spatie/laravel-paginateroute#38]
When I use 

`PaginateRoute::pageUrl($i)`

this not generate full url examle: http://example.com/news/page/2
byt only "?".

And this happens even when I use other url generator and page helper functions.

**Comment by michaloravec** [comment]
https://github.com/spatie/laravel-paginateroute/commit/8fe1ffb7047a987b4eea0873b4c90a6c3ab125c5#diff-0a427ca7b43101dac3c619568c5dfbf1

Lines 307 - 309 are bad, there are missing parentheses.

Original line 306 was good.

**Comment by sebastiandedeyne** [comment]
Thanks for the report, fixed in `2.6.2`

**Comment by michaloravec** [comment]
Ok, but problem now is with https://github.com/spatie/laravel-paginateroute/commit/e52dedf7b9ef65025e08dfd9ebe7f2a5c7af3015#diff-0a427ca7b43101dac3c619568c5dfbf1L305

use Request;

no use Illuminate\Http\Request;

**Comment by sebastiandedeyne** [comment]
Sorry, tagged a bit too fast. Should be working now.
