### ISSUE TITLE
Conflicting with spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-paginateroute#4]
Hi,
I am trying to use spatie/laravel-medialibrary and spatie/laravel-paginateroute on the same project but when i try to install spatie/laravel-medialibrary it gives me following error,

 Problem 1
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - Can only install one of: spatie/string[2.0.0, 1.9.1].
    - spatie/laravel-medialibrary dev-master requires spatie/string ^2.0 -> satisfiable by spatie/string[2.0.0].
    - Installation request for spatie/laravel-medialibrary dev-master -> satisfiable by spatie/laravel-medialibrary[dev-master].
    - Installation request for spatie/string == 1.9.1.0 -> satisfiable by spatie/string[1.9.1].

I checked and both the packages are using different versions of spatie/string

**Comment by freekmurze** [comment]
We will fix this later today, hang on...

**Comment by sebastiandedeyne** [comment]
Fixed in the latest release

https://github.com/spatie/laravel-paginateroute/releases/tag/1.4.0

**Comment by coding-sunshine** [comment]
Thanks very much
