### ISSUE TITLE
non-static methods

### ISSUE THREAD

**Issue by aidenko** [spatie/laravel-paginateroute#43]
Hi guys,

I am really surprised, but php complains about non-static methods.

public function boot()
    {
        PaginateRoute::registerMacros();

        parent::boot();
    }

this method is not static

**Comment by freekmurze** [comment]
You probably didn't import the facade.

**Comment by aidenko** [comment]
use Spatie\PaginateRoute\PaginateRoute;

public function boot()
{
PaginateRoute::registerMacros();

    parent::boot();
}

the method registerMacros() is not static

public function registerMacros(){
}

PHP 7.1

**Comment by freekmurze** [comment]
Replace the first line by

use PaginateRoute;

**Comment by aidenko** [comment]
yes, I have already seen that ide imported wrong namespace.

Thank you for the great package!
