### ISSUE TITLE
Declaration of App\Providers\RouteServiceProvider::boot ...

### ISSUE THREAD

**Issue by hamidhaghdoost** [spatie/laravel-paginateroute#45]
I have this error :
```
ErrorException thrown with message "Declaration of App\Providers\RouteServiceProvider::boot(Illuminate\Routing\Router $router) should be compatible with Illuminate\Foundation\Support\Providers\RouteServiceProvider::boot()"
```

**Comment by ashandi** [comment]
Try  to remove argument $router from boot function in RouteServiceProvider.

![screenshot_180](https://user-images.githubusercontent.com/14348708/33561299-58d9f09c-d923-11e7-8aaf-68487503f67c.png)

**Comment by sebastiandedeyne** [comment]
Yeah I guess Laravel changed that part. It's not necessary for us anyway :)
