### ISSUE TITLE
Class 'Illuminate\Routing\RouteParameterBinder' not found

### ISSUE THREAD

**Issue by knif3rdev** [spatie/laravel-paginateroute#47]
I installed the package but I got that error

Class 'Illuminate\Routing\RouteParameterBinder' not found

I tried to remove @include('pagination.default', ['paginator' => $lposts]) 

It will work. 

But I need to manually type the
http://mywebsite.com/page/2

How can I fix Class 'Illuminate\Routing\RouteParameterBinder' not found
 ?

**Comment by knif3rdev** [comment]
I am using laravel 5.2

**Comment by freekmurze** [comment]
We don't support L5.2 anymore.

**Comment by knif3rdev** [comment]
Oh, great.. Thanks anyway
