### ISSUE TITLE
Too many subpages, shattering layout. 

### ISSUE THREAD

**Issue by fredemagi** [spatie/laravel-paginateroute#50]
I facilitate the pagination with great joy, but when my dataset gets to large, I experience too many subpages, resulting in a pagination list that exceeds the borders in my layout. Is it in anyway possible to reduce the number og subpages and use dots instead? Like:
1 2 3 4 5 ... 56?

Regards.

**Comment by ashandi** [comment]
Hello!

I had the same problem and solved it as follows:
1. Pages links are rendered by next way:
```
{!! $paginator->render('layouts.pagination') !!}
```
2. Put the following code in `resources/views/layouts/pagination.blade.php` view:
```
@if ($paginator->hasPages())
    <ul class="pagination">
        {{-- Previous Page Link --}}
        @if (Paginator::hasPreviousPage())
            <li><a href="{{ Paginator::previousPageUrl() }}" rel="prev">&laquo;</a></li>
        @else
            <li class="disabled"><span>&laquo;</span></li>
        @endif

        {{-- Pagination Elements --}}
        @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
                <li class="disabled"><span>{{ $element }}</span></li>
            @endif

            {{-- Array Of Links --}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if (Paginator::isCurrentPage($page))
                        <li class="active"><span>{{ $page }}</span></li>
                    @else
                        <li><a href="{{ Paginator::pageUrl($page) }}">{{ $page }}</a></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        {{-- Next Page Link --}}
        @if (Paginator::hasNextPage($paginator))
            <li><a href="{{ Paginator::nextPageUrl($paginator) }}" rel="next">&raquo;</a></li>
        @else
            <li class="disabled"><span>&raquo;</span></li>
        @endif
    </ul>
@endif
```

This view based on default Laravel pagination view `vendor/laravel/framework/src/Illuminate/Pagination/resources/views/default.blade.php`

Maybe it's a good idea to add this view to spatie-package as default?

**Comment by fredemagi** [comment]
Hello, Ashandi,

How do you get access to $paginator? It is not available to my view?

Regards.

**Comment by ashandi** [comment]
By `$paginator` I mean collection which you want to paginate. For example
``` {!! $products->render('layouts.pagination') !!} ```

But in `resources/views/layouts/pagination.blade.php` the variable have to named `$paginator`.

Forgive me that I didn't explain it right away.

**Comment by fredemagi** [comment]
What is the fully qualified name for Paginator class? The class could not be found in the view. I copied your code to `resources/views/layouts/pagination.blade.php`. Furthermore, my route looks like: `Route::paginate('/find-match', 'MatchController@show')`.

**Comment by ashandi** [comment]
It is the facade from this package

```
// config/app.php

'aliases' => [
    ...
    'Paginator' => 'Spatie\PaginateRoute\PaginateRouteFacade',
];
```

**Comment by fredemagi** [comment]
I got it working! Thanks for your help :).

**Comment by fredemagi** [comment]
EDIT: Is there a way to determine a number of menu li's? Like: 1 2 3 ... 45 46 instead of 1 2 3 4 5 6 7 ... 45 46?
