### ISSUE TITLE
remove 'page' word from urls?

### ISSUE THREAD

**Issue by FaridAghili** [spatie/laravel-paginateroute#53]
Currently page links are like this:
`http://example.com/products/page/2`

Is there a way to change it so it create links like this?
`http://example.com/products/2`

I believe it's more SEO friendly, and also doesn't need to be translated for different locales.
The page number is the last URL segment (always).

**Comment by sebastiandedeyne** [comment]
This package is built with the idea that there's a keyword, I don't think we're going to add the option to drop it any time soon.

**Comment by michaloravec** [comment]
There is #35 available, but the test needs to be done for it
