### ISSUE TITLE
Compatibility issue with Laravel 5.5 +

### ISSUE THREAD

**Issue by yasirlateef** [spatie/laravel-paginateroute#56]
![screenshot from 2018-08-14 23-53-14](https://user-images.githubusercontent.com/14800695/44112133-bbb6eeec-a01d-11e8-8ca3-2feb0af90502.png)

After upgrading from Laravel 5.1 to 5.5, the package is generating an error for 'getURI' method. The package is really great and I would love to see it supporting current versions of laravel.

Upgrading core dependencies to 5.5 and Replacing the calls to `getUri()` method with `$this->router->current()->uri` should work. Just did it from the top of my head. 

Would love to hear from you.

**Comment by freekmurze** [comment]
Could you PR this fix?
