### ISSUE TITLE
Hide extra pages

### ISSUE THREAD

**Issue by bernardomacedo** [spatie/laravel-paginateroute#7]
Thanks again for the great code! Perhaps I am missing something.
Is there a way to have the same visual has the one originally generated by laravel?
I mean, When you have 150 results with the original paginator from laravel, and you decide to split in 10 records per page, the original laravel paginator decides to hide a couple from previous pages or next pages.
Eg:
Original Laravel on page 8:
<< 1 2 3 ... 7 8 9 ... 13 14 15 >>

With spatie:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

Also to decide to place a class or ID to the main <ul></ul> generated would be optimal.

Thanks

**Comment by sebastiandedeyne** [comment]
This hasn't been added yet. I probably won't be implementing it in the near future either, but would gladly accept a pull request.

**Comment by bernardomacedo** [comment]
How do I pull request? GitHub for mac says:
You may not have permission to access laravel-paginateroute. Check Preferences to make sure you’re still logged in.

**Comment by sebastiandedeyne** [comment]
You're going to have to fork the repository to your own account first, and push the changes there. Afterwards you can send a PR from that repository to this one.

https://help.github.com/articles/using-pull-requests/

—Sebastian

**Comment by bernardomacedo** [comment]
Thanks! I will try to add the changes needed! Cheers

Bernardo Sousa de Macedo

**Comment by hungnm144** [comment]
Too simple to solve this problem
```<ul class="pagination">
    @if(PaginateRoute::hasPreviousPage())
        <li><a href="{{ PaginateRoute::previousPageUrl() }}" rel="prev">&laquo;</a></li>
    @else
        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
    @endif

    @php
        $lastPage = $paginator->lastPage();
        $currentPage = $paginator->currentPage();
        $count = $paginator->count();
    @endphp

    @for ($page = 1; $page <= $lastPage; $page++)
        {{--  Use three dots when current page is greater than 2.  --}}
        @if ($currentPage > 2 && $page === 2)
            <li class="disabled"><span aria-hidden="true">...</span></li>
        @endif

            {{--  Show active page else show the first and last two pages from current page.  --}}
            @if ($page == $currentPage)
                <li class="active">
                    <span aria-hidden="true">{{ $page }}</span>
                </li>
            @elseif ($page === 1 || $page === $currentPage + 1 || $page === $currentPage + 2 || $page === $currentPage - 1 || $page === $currentPage - 2 || $page === $lastPage)
                <li>
                    <a href="{{ PaginateRoute::pageUrl($page) }}">{{ $page }}</a>
                </li>
            @endif

        {{--  Use three dots when current page is awasy from end.  --}}
        @if ($currentPage < $count - 2 && $page === $count - 1)
            <li class="disabled"><span aria-hidden="true">...</span></li>
        @endif

    @endfor

    @if(PaginateRoute::hasNextPage($paginator))
        <li><a href="{{ PaginateRoute::nextPageUrl($paginator) }}" rel="next">&raquo;</a></li>
    @else
        <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
    @endif
</ul>
```
