### ISSUE TITLE
How to use pagitnation with Cache?

### ISSUE THREAD

**Issue by amviro** [spatie/laravel-paginateroute#8]
Hello,
How should I use pagination query with Cache?
The following query return same cached results

```
$blogs= Cache::remember('blogs', 720,function() {
            return Blog::with(['comments'])->simplePaginate(5);
        });
```

Regards

**Comment by sebastiandedeyne** [comment]
You'll need to add the current page number to the cache key or it will always return the results of the first page that gets cached.

``` php
Cache::remember('blogs'.PaginateRoute::currentPage(), ...);
```
